### ISSUE TITLE
Don't spam callback URL with Progress callbacks

### ISSUE THREAD

**Issue by thomshutt** [livepeer/catalyst-api#104]
Currently we send one after every transcoded segment, but should figure out a way to do 1 every X seconds.

@victorges suggested:

> you could probably copy 100% of this progress reporter from the task-runner (we could move it to some shared utils lib at some point)
https://github.com/livepeer/task-runner/blob/13db95e3b5c784119d200629e443a32349d899d4/task/progress.go#L35
> actually, would only need to change what it does when it "sends a progress update" here
https://github.com/livepeer/task-runner/blob/13db95e3b5c784119d200629e443a32349d899d4/task/progress.go#L115

**Comment by red-0ne** [comment]
Closed by #218
cc @thomshutt
