### ISSUE TITLE
Handle "Output Locations" array properly

### ISSUE THREAD

**Issue by thomshutt** [livepeer/catalyst-api#130]
Currently we just grab the first location and use it for both source segments and transcoded renditions.

We should:

- Segmenting Stage: Iterate over the array and find the one that's marked as "source segments". Error for now if there's more than one of these
- Transcoding Stage: Push to all that are marked for "transcoded segments" 
- Return the list of outputs at the end in the same order we received them

**Comment by emranemran** [comment]
After discussing with @victorges, decided it was best to do this in two PRs. First PR is to just update the directory structure into what Studio expects. The definition of the directory structure is pretty loose but Victor suggested a good structure which is implemented in this PR: 
https://github.com/livepeer/catalyst-api/pull/133
https://github.com/livepeer/catalyst-api/issues/134

A follow up PR will be used for implementing the ideas in this ticket. 

The main reasons for splitting up this ticket: 
* We currently only have one output type (`object_store`) in the request and that's all we need for immediate use (esp for this week's goals)
* Limit the changes in the PR as it was getting larger.
