### ISSUE TITLE
Support IPFS and Arweave URLs in Catalyst API

### ISSUE THREAD

**Issue by thomshutt** [livepeer/catalyst-api#141]
Related: https://github.com/livepeer/task-runner/issues/79

For the initial version, we should just pick a free gateway and convert them to HTTP(s) URLs when they first reach Catalyst API.

**Comment by yondonfu** [comment]
This is also needed to support retrying with multiple gateways. At the moment, task-runner constructs the HTTP URL with a single [gateway](https://github.com/livepeer/task-runner/blob/7438da0ffc1e2552dc4481f8b8a67b7a26c399ab/task/upload.go#L180) and there is no retry mechanism with other gateways.
