### ISSUE TITLE
Mist removes the last segment of video

### ISSUE THREAD

**Issue by thomshutt** [livepeer/catalyst-api#142]
Example: https://playback.livepeer.monster:10443/hls/asset+1a25suea997u0x67/index.m3u8

The segment is there in the source and rendition manifests, but Mist removes it when playing back

**Comment by Thulinma** [comment]
Can you define "playing back" in this context? What are the input (I assume HLS input) and output used?

**Comment by thomshutt** [comment]
"Playing back" being the manifest that Mist returns. Input is an HLS manifest + DTSH file in Google Storage.

**Comment by thomshutt** [comment]
Closing as this is now being tracked elsewhere
