### ISSUE TITLE
Catalyst tries to transcode before upload is complete

### ISSUE THREAD

**Issue by thomshutt** [livepeer/catalyst-api#196]
Because Mist sends us the RECORDING_END trigger before the segmenting uploads are complete, there's sometimes a race condition whereby we'll try to transcode with files that aren't in storage yet.

Initial strategy should be to wait 10s between segmenting and transcoding before coming up with a better approach.

**Comment by Thulinma** [comment]
Better idea: a new trigger that gets executed for each upload, and waits for it to finish before firing. Then just wait for all uploads to complete?

**Comment by thomshutt** [comment]
@Thulinma that would be ideal

**Comment by thomshutt** [comment]
This has been "solved" in the interim with retries and backoffs
