### ISSUE TITLE
No Os with required capabilities gets reported as "No sessions available"

### ISSUE THREAD

**Issue by thomshutt** [livepeer/catalyst-api#229]
When trying to transcode e.g a format that no Os in the network support, we get a `no sessions available` error back from the broadcaster rather than a more specific one such as `pixel format not supported` that occurs when an O tries and fails to transcode a segment.

The correct solution will probably be to try and distinguish in the Broadcaster between a legitimate capacity issue and a capability issue, then propagate that error back through Catalyst API to the caller.

**Comment by yondonfu** [comment]
For reference:

- B performs a capability check for an O during discovery [here](https://github.com/livepeer/go-livepeer/blob/fa3564565e7aa7d40be14502b8a217c7a541b740/discovery/discovery.go#L98)
- A CapabilityComparator (i.e. a list of capabilities that can be compared against another list of capabilities) is passed into [GetOrchestrators()](https://github.com/livepeer/go-livepeer/blob/fa3564565e7aa7d40be14502b8a217c7a541b740/discovery/discovery.go#L57) which is called during discovery time and which should be generated via [JobCapabilities()](https://github.com/livepeer/go-livepeer/blob/fa3564565e7aa7d40be14502b8a217c7a541b740/core/capabilities.go#L229) which should return capabilities that are required for a job (i.e. a segment to be transcoded)
- The capability check will fail if the capabilities advertised by the O (via OrchestratorInfo.Capabilities) do not fulfill the requirements of the capabilities passed to GetOrchestrators(). So, a few tricky things to consider here include:
    - What if the O is missing multiple capabilities? How should that info be propagated to a caller?
    - What if no Os are available because some are missing capability X and some are missing capability Y? How should that info be propagated to a caller?
