### ISSUE TITLE
Mist processes don't always terminate 

### ISSUE THREAD

**Issue by Quintendos** [livepeer/catalyst-api#247]
It seems to be this specific process: /usr/local/bin/MistInMP4 -H s3+[https://GOOG1EI5CHQ5WMAIXDXXCJ4SZTIWM3A2SYONENKAGND7AE352N3IIVGWPXCSA:6hytghQuCjN4JS611Jue7meoczAxlYi1xiRBhlpW@storage.googleapis.com/lp-us-catalyst-vod-monster/hls/e13392pc0e38musn/source/arweave-source.mp4](https://GOOG1EI5CHQ5WMAIXDXXCJ4SZTIWM3A2SYONENKAGND7AE352N3IIVGWPXCSA:6hytghQuCjN4JS611Jue7meoczAxlYi1xiRBhlpW@storage.googleapis.com/lp-us-catalyst-vod-monster/hls/e13392pc0e38musn/source/arweave-source.mp4)
 -F s3+[https://GOOG1EI5CHQ5WMAIXDXXCJ4SZTIWM3A2SYONENKAGND7AE352N3IIVGWPXCSA:6hytghQuCjN4JS611Jue7meoczAxlYi1xiRBhlpW@storage.googleapis.com/lp-us-catalyst-vod-monster/hls/e13392pc0e38musn/source/arweave-source.mp4](https://GOOG1EI5CHQ5WMAIXDXXCJ4SZTIWM3A2SYONENKAGND7AE352N3IIVGWPXCSA:6hytghQuCjN4JS611Jue7meoczAxlYi1xiRBhlpW@storage.googleapis.com/lp-us-catalyst-vod-monster/hls/e13392pc0e38musn/source/arweave-source.mp4)
 -g

**Comment by stronk-dev** [comment]
Issue seems to be that the input file has a size of 0 bytes. The MistInMP4 process does not seem to deal with this correctly and keeps trying to read until it reads 16 bytes of data. Should be an easy fix
