### ISSUE TITLE
Add a FAILED trigger with information about whether there was a Source / Output failure

### ISSUE THREAD

**Issue by Quintendos** [livepeer/catalyst-api#248]
Segmenting 

related: https://www.notion.so/livepeer/Segmenting-delay-of-1-minute-with-larger-files-may-cause-time-out-on-Studio-side-e21861ed048f48ef8475a85246edbc30

https://www.notion.so/livepeer/Catalyst-VOD-da8af0d46ac3487eb7f9c9511a53a19e#43beb7fc1f804103a88a4dee0496a3dd

**Comment by stronk-dev** [comment]
Trigger for unsupported input track types passed testing: https://github.com/DDVTECH/DMS/tree/UnsupportedTrack
Trigger for failing pushes up next...

**Comment by stronk-dev** [comment]
Did not pass testing yet. Was confused with the `unsupported track` trigger.
Currently in testing with some minor feedback, afte that code review before merging it upstream, so not available yet
