### ISSUE TITLE
Mist - iOS mov recording gives timestamp issue on playback

### ISSUE THREAD

**Issue by Quintendos** [livepeer/catalyst-api#250]

**Comment by AlexKordic** [comment]
Testing playback directly from http link is wrong because `.dtsh` file can't be written to the storage. In further testing we should upload the `09faf2ulc3ch89mf` asset to S3 storage.

**Comment by AlexKordic** [comment]
We noticed missing trailing frames in segments produced by MistServer.
Using `livingroom.mov` as a source each of 3 segments is missing last 3 frames. Happens to be `B` frames.

**Comment by AlexKordic** [comment]
The issue is in TS+M3U8 output format logic of MistServer

**Comment by AlexKordic** [comment]
discussion: https://discord.com/channels/423160867534929930/1052539353726992384

**Comment by AlexKordic** [comment]
fix is here: https://github.com/livepeer/lpms/pull/363
