### ISSUE TITLE
Test LPMS refactoring on staging

### ISSUE THREAD

**Issue by Quintendos** [livepeer/catalyst-api#305]
[1] https://github.com/livepeer/lpms/pull/347
[2] https://github.com/livepeer/lpms/pull/348

(blocks transcoding work Diederik)

**Comment by mjh1** [comment]
@thomshutt is this the correct place to add this env variable? orchestrator section..? https://github.com/livepeer/livepeer-infra/commit/e411d494bb171cb9d998c4138ac71d40d2dc7338

**Comment by thomshutt** [comment]
I _think_ so, you should check if we have logging to confirm it's working though (and add it if we don't)

**Comment by mjh1** [comment]
> I _think_ so, you should check if we have logging to confirm it's working though (and add it if we don't)

@thomshutt do you think this will be ok: https://github.com/livepeer/lpms/pull/362/files
Obviously not great having a log line for every transcode but the log line would go away eventually when we remove the old implementation. Easiest alternative I can think of is just reading the same environment variable on startup in go-livepeer and logging it there 🤔

**Comment by thomshutt** [comment]
@mjh1 Yeah, that's fine - I just approved. In the grand scheme of the amount of logging we do, one line per transcode is fine.

**Comment by mjh1** [comment]
This was rolled out to staging today. Initial tests aren't showing any issues 👍 

Confirmed with the log line that it's definitely in action:
```
~ kubectl logs staging-livepeer-orchestrator-1 | grep "LPMS new transcode enabled"
I0110 10:20:41.029146       1 ffmpeg.go:970] LPMS new transcode enabled
```

**Comment by thomshutt** [comment]
Holding off until we find the cause of extra frames that @AlexKordic saw being added in some cases
