### ISSUE TITLE
Emit metrics after segmenting failure

### ISSUE THREAD

**Issue by thomshutt** [livepeer/catalyst-api#386]
Currently if Mist fails early enough (i.e we catch the failure in one of the triggers), we don't write any metric to Prometheus.

**Comment by mjh1** [comment]
I looked at an example of this in prod and saw that after the "segmenting failed" error we then get a log line "Finished job and deleted from job cache" from [here](https://github.com/livepeer/catalyst-api/blob/cbcd4f4d37a1ff27484319c42de8ce6252cb77bd/pipeline/coordinator.go#L432) where we also emit the vod pipeline metrics so doesn't that mean we're covered? Or are we saying we want an extra metric to say specifically "segmenting failure", that could be a tag on the existing metrics i guess.

[Vod example from loki](https://eu-metrics-monitoring.livepeer.live/grafana/explore?orgId=1&left=%7B%22datasource%22:%22P8E80F9AEF21F6940%22,%22queries%22:%5B%7B%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22P8E80F9AEF21F6940%22%7D,%22editorMode%22:%22code%22,%22expr%22:%22%7Bapp%20%3D~%20%5C%22catalyst%7Ccatalyst-api%5C%22%7D%20%7C%3D%20%5C%22request_id%3Dbg_ddceccfa%5C%22%22,%22queryType%22:%22range%22,%22refId%22:%22A%22%7D%5D,%22range%22:%7B%22from%22:%221678355619545%22,%22to%22:%221678357286482%22%7D%7D)

**Comment by thomshutt** [comment]
@mjh1 Great! Sounds like this was maybe fixed during the pipeline work then - I'll close
