### ISSUE TITLE
verify MP4 renditions on S3 before signaling Studio

### ISSUE THREAD

**Issue by emranemran** [livepeer/catalyst-api#389]
When the Mist/Mediaconvert transcode job is completed, catalyst-api should check that the MP4 output files are generated before responding to Studio. The Studio logic can then mark these files as "existing" so that SDK knows which renditions are available.

**Comment by mjh1** [comment]
@emranemran should this just be an http HEAD request on the URLs and check for a 2xx?

**Comment by mjh1** [comment]
In this ticket I'll also include implementing fixing [profiles_count field](https://github.com/livepeer/catalyst-api/blob/6c26531a761d5fa4003a8f056df19d3c8a98cb04/pipeline/coordinator.go#L392) for the postgres metrics to be the number of output profiles rather than requested profiles.
