### ISSUE TITLE
catalyst <-> studio integration for short form videos

### ISSUE THREAD

**Issue by gioelecerati** [livepeer/catalyst-api#400]
After a sync with @emranemran , some work is needed to be done on Studio Task Runner and Catalyst for short form videos, specifically:

- add `AutoMP4s: bool` in `api/vod` in both the request studio & the catalyst-api struct
- Add `Mp4Outputs` to TranscodeStatusMessage from Catalyst to Studio
- Potentially, before populating the struct of TranscodeStatusMessage check on the storage if the mp4 is there (may require more time)
- `api/transcode` endpoint need to recognize the AutoMP4s

**Comment by emranemran** [comment]
Adding some context for @mjh1:

> add AutoMP4s: bool in api/vod in both the request studio & the catalyst-api struct
- If this flag is set, then we should enable MP4 output regardless of duration threshold (currently set to 2min)

> Add Mp4Outputs to TranscodeStatusMessage from Catalyst to Studio

- When a job is done, we call: 
`func (c *Coordinator) finishJob(job *JobInfo, out *HandlerOutput, err error) {`
which calls: 
`        job.statusClient.SendTranscodeStatus(tsm)`.
We need to update `TranscodeStatusMessage` and specifically `OutputVideoFile` to include an `MP4OutputLocation` (instead of `MP4Outputs` field that indicates an MP4 was generated for that specific rendition. Since we assume mediaconvert will succeed, perhaps for now we just can auto-generate the paths based on what we know in catalyst-api. A follow-up ticket can be used to verify that the mp4s were successfully placed in the object-store. @mjh1 mind filing a separate ticket if this seems to be a requirement when you make these changes? 

> Potentially, before populating the struct of TranscodeStatusMessage check on the storage if the mp4 is there (may require more time)
- same comment as previous

> api/transcode endpoint need to recognize the AutoMP4s
- Same as first point -- this endpoint should support the same `AutoMP4` field in the request and also update the same job structs that will get passed to the transcode functions.

**Comment by victorges** [comment]
@gioelecerati @emranemran So is the idea to add a new `output_location` on the upload request payload, or to just toggle `AutoMP4s` on the existing `output_location` that we already send? (which is only for HLS today and sends an `index.m3u8` URL for the path)

I think the first (adding a new `output_location`) would need some logic on catalyst side to make sure outputs are generated in the exact same order as the requested `output_locations`, or to figure out some other way to match requests with outputs as currently we only really have the order (so `task-runner` is implemented like that).

The latter (just toggling `AutoMP4s`) might need to change `task-runner` a bit more on how it handles the outputs,
as in `transcodeStatusMessage.outputs[].videos` being the source of multiplicity, not `transcodeStatusMessage.outputs itself` (or maybe both). More specifically, changing the logic of this loop here: 
https://github.com/livepeer/task-runner/blob/51558d77a00e4e09a23a5f429da5ed3ae9a4baaf/task/upload.go#L210

I'm fine with either direction, but if we go with `AutoMP4s` on the same `output_location` that already exists today, I'd suggest changing [the `path` that we send on that request](https://github.com/livepeer/task-runner/blob/51558d77a00e4e09a23a5f429da5ed3ae9a4baaf/task/upload.go#L403) to not include the `index.m3u8` file name, as that wouldn't make sense anymore (e.g. what if we're not even doing HLS, only MP4s? but then have to send a `index.m3u8` url?). 
**It could be just the folder instead**! And catalyst handles the internal structure of the files that it creates and then returns their full paths in the `tsm.outputs[].videos` ✨

This can be considered just a tech debt for the future and we keep Catalyst with some logic to always remove the last element of the path (if it is `index.m3u8`) and treating the request argument as just a folder instead. On `task-runner` it's really easy to change, just a helper func, but it might be trickier in Catalyst.

**Comment by mjh1** [comment]
@victorges @gioelecerati I've put together an example of the status message showing how I'm thinking of representing the MP4 outputs, this is just using the existing fields we have on the structs. Let me know if it sounds ok for now in terms of task-runner and studio.
```
{
    "outputs": [
        {
            "type": "object_store",
            "manifest": "https://foo.bar/index.m3u8",
            "videos": [
            ]
        },
        {
            "type": "object_store",
            "manifest": "",
            "videos": [
                {
                    "type": "mp4",
                    "size": "123456",
                    "location": "https://foo.bar/static360p0.mp4"
                },
                {
                    "type": "mp4",
                    "size": "1234567",
                    "location": "https://foo.bar/static720p0.mp4"
                }
            ]
        }
    ]
}
```
- I've left the HLS output the same as now, the videos field is left empty.
- I'm thinking of leaving the manifest field blank for mp4 outputs as it doesn't apply.

**Comment by victorges** [comment]
I think it looks good. What would the corresponding request for that output
look like? And how should the client match the request output locations
with the response outputs?

**Comment by mjh1** [comment]
@victorges I'd vote for your suggestion of switching the output location field on the request to be a "folder" instead, then we can put both the hls index file and the mp4 outputs there. So the request can remain the same as now other than the meaning of the location field.

**Comment by gioelecerati** [comment]
> @victorges @gioelecerati I've put together an example of the status message showing how I'm thinking of representing the MP4 outputs, this is just using the existing fields we have on the structs, not adding anything new. Let me know if it sounds ok for now in terms of task-runner and studio.
> 
> ```
> {
>     "outputs": [
>         {
>             "type": "object_store",
>             "manifest": "https://foo.bar/index.m3u8",
>             "videos": [
>             ]
>         },
>         {
>             "type": "object_store",
>             "manifest": "",
>             "videos": [
>                 {
>                     "type": "mp4",
>                     "size": "123456",
>                     "location": "https://foo.bar/static360p0.mp4"
>                 },
>                 {
>                     "type": "mp4",
>                     "size": "1234567",
>                     "location": "https://foo.bar/static720p0.mp4"
>                 }
>             ]
>         }
>     ]
> }
> ```
> 
> * I've left the HLS output the same as now, the videos field is left empty.
> * I'm thinking of leaving the manifest field blank for mp4 outputs as it doesn't apply.

Looks good! WDYT if the manifest key is missing instead of blank when mp4? I am fine with this either way.
In a second moment I would probably move the type on the root level of the object, so task-runner does not need to iterate the videos to get it, but for now it's ok, let's not change the structs

**Comment by victorges** [comment]
> [@victorges](https://github.com/victorges) I'd vote for your suggestion of switching the output location field on the request to be a "folder" instead, then we can put both the hls index file and the mp4 outputs there. So the request can remain the same as now other than the meaning of the location field.

I think there should be only `outout` in the response then if we send a single `output_location` in the request with a folder location instead. Then it's a single response with both the manifest and the video files. With the manifest only present if HLS was requested, and files only if MP4 was requested (although we could return a file for the HLS playlist manifest as well).

**Comment by mjh1** [comment]
@gioelecerati omitting the manifest key sounds good, will do that.

@victorges would you mind re-arranging my example to make it clear what you mean? i think it makes sense though, but i'll follow up with another PR after https://github.com/livepeer/catalyst-api/pull/411 if that's ok
