### ISSUE TITLE
ffprobe fails if moov box is at the end of the file

### ISSUE THREAD

**Issue by emranemran** [livepeer/catalyst-api#401]
If the moov atom flag is at the end of the file (or if the file is a fragmented mp4), then this go-ffprobe lib will not be able to generate the output correctly as it will exit before it reaches the end of file.

**Comment by victorges** [comment]
Does this also happen in that task-runner probing? I don't remember seeing (m)any files failing ffprobe consistently like that. But maybe most of them do have the MOOV at the beginning?

**Comment by emranemran** [comment]
We currently copy the file to S3 and we always probe the S3 source URL which supports range requests - so moov atom location doesn't matter anymore. Closing this this ticket.
