### ISSUE TITLE
videoSpec details for transcoded mp4 outputs

### ISSUE THREAD

**Issue by gioelecerati** [livepeer/catalyst-api#444]
Right now, we're only sending Studio basic info about transcoded MP4s like size, width, height, and bitrate. But as discussed async, we thought it could be a good idea to give Studio the full ffprobe JSON output for these files, or additional useful information.

This could include some edits on Studio `playback` endpoint adding a `details` parameter to retrieve this information, which would be nested under a `videoSpec` key.

Leaving this ticket as reminder for this optimization

**Comment by emranemran** [comment]
Related to https://github.com/livepeer/catalyst-api/issues/417
