### ISSUE TITLE
catalyst-api will flush existing trigger handlers and replace with mist triggers

### ISSUE THREAD

**Issue by joegraviton** [livepeer/catalyst-api#782]
In our dev env, we are running catalyst in docker with this image:

```
# https://hub.docker.com/r/livepeerci/catalyst/tags?name=main
# livepeerci/catalyst:main on 2023-07-27
FROM livepeerci/catalyst@sha256:472f334a69bbb05e2a0273530f6a5454c810f63ce2fe8b48c883faec70bc01a5
```

We defined some custom trigger handlers in our catalyst.json, and observe them with `watch "grep handler /tmp/catalyst.json"`  cmd:

At first, when container starts, it shows this:

```
         ...
          "handler": "/app/STREAM_BUFFER.py",
          "handler": "/app/STREAM_SOURCE.py",
          "handler": "http://127.0.0.1:7979/STREAM_SOURCE",
          ...
```

Wait for 1 minutes or so, without doing anything, the output changes to this:

![2023-07-31_10-57](https://github.com/livepeer/catalyst-api/assets/101067071/051b35be-4974-4240-8a50-56d5a5f02412)

All the custom ones are gone.

The previous image we were using is this one and have no such issue:
```
# https://hub.docker.com/r/livepeerci/catalyst/tags?name=main
 # livepeerci/catalyst:main on 2023-06-17
FROM livepeerci/catalyst@sha256:eac634a54b2bd1c954c329b0a5fc686af7e34eb051c2130305c3359537b9530c
```

This seems relate to this change (738c31b2b3de066f5c56d109878ed62badbc563a) introduced on 2023-06-30, but I didn't dig too far:

![image](https://github.com/livepeer/catalyst-api/assets/101067071/1d75164b-d25d-4bc0-b584-ac179355eba9)

**Comment by iameli-streams** [comment]
@joegraviton Got it, yeah. This was some intentional behavior on our end to clean up some old triggers; in our use case we want catalyst-api to take full control of those. But those are cleaned up now; I can make it so it doesn't clobber existing hooks anymore.

**Comment by joegraviton** [comment]
@iameli-streams  thanks for the info. 
Feel free to merge your PR https://github.com/livepeer/catalyst-api/pull/785/files
we can add the mist triggers on our end.
Thank you!

**Comment by joegraviton** [comment]
Issue fixed with the new `--no-mist-trigger-setup` option, I will close this. thanks.
